import StyleDictionary from "style-dictionary";

/**
 * Style Dictionary 4 build.
 *
 * Inputs:  tokens/**\/*.tokens.json  (DTCG 2025.10 format)
 * Outputs:
 *   packages/css/src/tokens.css          — CSS custom properties (rem for space/font-size, @supports gamut)
 *   packages/css/src/tailwind-theme.css  — Tailwind v4 @theme block
 *   packages/tokens/dist/tokens.json     — resolved token tree (JS consumers)
 */

// ─── Custom transform: px → rem for space.* and font.size.* ─────────────────
// Runs AFTER the built-in size/px transform which converts DTCG dimension
// objects to "Npx" strings. This pass converts those strings to rem.
StyleDictionary.registerTransform({
  name: "size/rem",
  type: "value",
  filter: (token) => {
    const type = token.$type ?? token.type;
    if (type !== "dimension") return false;
    const path = token.path.join(".");
    return path.startsWith("space.") || path.startsWith("font.size");
  },
  transform: (token) => {
    const val = String(token.value ?? "");
    if (val.endsWith("px")) {
      const px = parseFloat(val);
      if (!isNaN(px) && px !== 0) return `${+(px / 16).toFixed(4).replace(/\.?0+$/, "")}rem`;
      if (px === 0) return "0";
    }
    return val;
  },
});

// ─── Custom transform group: css + rem ───────────────────────────────────────
StyleDictionary.registerTransformGroup({
  name: "css/rem",
  transforms: [
    "attribute/cti",
    "name/kebab",
    "time/seconds",
    "html/icon",
    "size/px",    // converts DTCG dimension objects to "Npx" strings
    "size/rem",   // then converts qualifying tokens to rem
    "color/css",
    "asset/url",
    "fontFamily/css",
    "cubicBezier/css",
    "strokeStyle/css/shorthand",
    "border/css/shorthand",
    "typography/css/shorthand",
    "transition/css/shorthand",
    "shadow/css/shorthand",
  ],
});

// ─── Custom format: CSS custom properties with sRGB + oklch gamut fallback ───
// Color tokens emit two blocks:
//   1. :root { --token: #hex; }          — sRGB fallback, always applies
//   2. @supports (color: oklch(0 0 0)) { :root { --token: oklch(...); } }
// Non-color tokens are emitted once in block 1 at their transformed value.
StyleDictionary.registerFormat({
  name: "css/color-gamut",
  format: ({ dictionary, options }) => {
    const selector = options?.selector ?? ":root";

    const isColor = (t) => (t.$type ?? t.type) === "color";

    const colorTokens = dictionary.allTokens.filter(isColor);
    const otherTokens = dictionary.allTokens.filter((t) => !isColor(t));

    // Extract sRGB hex from our DTCG $value.hex field, falling back to
    // resolved value if hex is absent (covers aliased tokens that resolved
    // to a hex string already).
    const hexOf = (token) => {
      const orig = token.original?.$value ?? token.original?.value;
      if (orig && typeof orig === "object" && orig.hex) return orig.hex;
      // If the resolved value looks like a hex string use it directly
      const v = String(token.value ?? "");
      if (/^#[0-9a-f]{3,8}$/i.test(v)) return v;
      return token.value; // last resort: use whatever SD resolved
    };

    const lines = [
      "/* Generated by Style Dictionary — do not edit */",
      `${selector} {`,
      ...otherTokens.map((t) => `  --${t.name}: ${t.value};`),
      ...colorTokens.map((t) => `  --${t.name}: ${hexOf(t)};`),
      "}",
      "",
      "/* Wide-gamut color override — oklch values on supporting browsers */",
      "@supports (color: oklch(0 0 0)) {",
      `  ${selector} {`,
      ...colorTokens.map((t) => `    --${t.name}: ${t.value};`),
      "  }",
      "}",
    ];

    return lines.join("\n") + "\n";
  },
});

// ─── Build config ─────────────────────────────────────────────────────────────

const sd = new StyleDictionary({
  log: { verbosity: "verbose" },

  source: ["tokens/**/*.tokens.json"],

  usesDtcg: true,

  platforms: {
    css: {
      transformGroup: "css/rem",
      prefix: "ds",
      buildPath: "packages/css/src/",
      files: [
        {
          destination: "tokens.css",
          format: "css/color-gamut",
          options: {
            selector: ":root",
            outputReferences: false,
          },
        },
      ],
    },

    tailwind: {
      transformGroup: "css/rem",
      prefix: "ds",
      buildPath: "packages/css/src/",
      files: [
        {
          destination: "tailwind-theme.css",
          format: "css/variables",
          options: {
            selector: "@theme",
            outputReferences: false,
          },
          filter: (token) => {
            const path = token.path.join(".");
            return (
              path.startsWith("color.") ||
              path.startsWith("space.") ||
              path.startsWith("radius.") ||
              path.startsWith("font.size") ||
              path.startsWith("shadow.")
            );
          },
        },
      ],
    },

    json: {
      transformGroup: "js",
      buildPath: "packages/tokens/dist/",
      files: [
        {
          destination: "tokens.json",
          format: "json/nested",
        },
      ],
    },
  },
});

await sd.cleanAllPlatforms();
await sd.buildAllPlatforms();

console.log("\n✓ Token build complete");
console.log("  packages/css/src/tokens.css        (sRGB fallback + @supports oklch)");
console.log("  packages/css/src/tailwind-theme.css");
console.log("  packages/tokens/dist/tokens.json");
