import path from "node:path";

function labelForKind(kind) {
  return kind
    .split("-")
    .map((part, index) =>
      index === 0 ? `${part[0].toUpperCase()}${part.slice(1)}` : part,
    )
    .join(" ");
}

function relativeLink(artifactPath) {
  return path.posix.relative("design", artifactPath);
}

export function renderIndex(
  manifest,
  skillIds = [],
) {
  const rows = manifest.artifacts.map((artifact) => {
    const label = labelForKind(artifact.kind);
    const link = relativeLink(artifact.path);
    return `| ${label} | ${artifact.role} | ${artifact.status} | [${link}](${link}) |`;
  });
  const flowRoot = manifest.flow_policy.roots[0];
  const prototypeRoot = manifest.prototype_policy.roots[0];

  return [
    "<!-- Generated by The Silver Design Framework. Edit design/manifest.yaml, not this file. -->",
    "",
    "# Design index",
    "",
    `Workspace: **${manifest.workspace.name}** (\`${manifest.workspace.scope}\`)`,
    "",
    "| Kind | Role | Status | Canonical location |",
    "| --- | --- | --- | --- |",
    ...rows,
    "",
    `Flow root: \`${flowRoot}/\``,
    `Default flow view: \`${manifest.flow_policy.default_view}\``,
    "",
    `Prototype root: \`${prototypeRoot}/\``,
    `Default constraint profile: \`${manifest.prototype_policy.default_profile}\``,
    "",
    skillIds.length > 0
      ? `Installed project skills: ${skillIds.map((id) => `\`${id}\``).join(", ")}`
      : "Installed project skills: none",
    "",
  ].join("\n");
}
