#!/usr/bin/env node
// Generated by The Silver Design Framework.
import path from "node:path";
import { fileURLToPath } from "node:url";

const skillDirectory = new URL("..", import.meta.url);
const skillId = path.basename(fileURLToPath(skillDirectory).replace(/[\\/]$/, ""));

let runtime;
let failure;
for (const specifier of [
  "silver-design-framework/framework/runtime/invoke-skill.mjs",
  "../../../.silver/runtime/invoke-skill.mjs",
]) {
  try {
    runtime = await import(specifier);
    break;
  } catch (error) {
    failure = error;
  }
}

if (!runtime) {
  console.error(
    `Cannot load the Silver runtime from this workspace: ${failure.message}\n` +
      `Run .silver/bin/silver invoke ${skillId} <request.json> .`,
  );
  process.exit(2);
}

runtime.runSkillCli({ skillDirectory, args: process.argv.slice(2) }).then((code) => {
  process.exitCode = code;
});
