import { mkdir, readFile, readdir } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { parse, stringify } from "yaml";

import {
  copyNewTree,
  exists,
  integrity,
  listTopLevel,
  readUtf8,
  resolveInside,
  treeIntegrity,
  writeNewFile,
  writeUtf8,
} from "./lib/files.mjs";
import { renderIndex } from "./lib/index.mjs";
import {
  WORKSPACE_PRACTICE_OVERLAY_PATH,
  ensureGitignoreEntries,
  resolveSharedStudioVoice,
  writeWorkspacePracticeOverlay,
} from "./practice-overlay.mjs";
import { validateSchema } from "./lib/schemas.mjs";
import {
  CLAUDE_MEMORY_PATH,
  LAUNCHER_CMD_PATH,
  LAUNCHER_PATH,
  mergeClaudeMemory,
  renderClaudeBlock,
  writeClaudeSkillLinks,
  writeLauncher,
} from "./agent-adapters.mjs";
import {
  FRAMEWORK_VERSION,
  LOCAL_SOURCE_REFERENCE,
} from "./version.mjs";

const installerRoot = path.dirname(fileURLToPath(import.meta.url));
const repositoryRoot = path.resolve(installerRoot, "..");
const templateRoot = path.join(installerRoot, "templates", "blank-workspace");
export const INITIAL_SKILL_IDS = [
  "what-now",
  "brand",
  "product",
  "voice",
  "principles",
  "theme",
  "system",
  "research",
  "synthesize",
  "ideate",
  "specify",
  "flow",
  "sketch",
  "component",
  "prototype",
  "evaluate",
  "pitch",
  "implement",
  "map",
  "practice-review",
  "design-check",
];
const allowedBlankEntries = new Set([
  ".DS_Store",
  ".git",
  ".gitignore",
  "LICENSE",
  "LICENSE.md",
  "README.md",
  // Agent instruction files and host configuration do not make a folder an
  // existing codebase, and a Silver workspace adds its own.
  ".claude",
  "AGENTS.md",
  "CLAUDE.md",
  "CLAUDE.local.md",
]);
export const SEEDED_TEMPLATES = [
  "design/brand.md",
  "design/product.md",
  "design/voice.md",
  "design/design-principles.md",
  "design/system/README.md",
  "design/flows/README.md",
  "design/decisions/README.md",
  "design/integrations/README.md",
  "design/guidance/README.md",
  "design/guidance/sources.yaml",
  "design/sources/README.md",
  "design/sources/sources.yaml",
  "design/contexts/README.md",
  "design/contexts/default.yaml",
  "design/contexts/default-expression.yaml",
  "design/maps/README.md",
  "design/TRACE.md",
  "design/assets/catalog.json",
  "design/assets/README.md",
  "design/presentation-kit/kit.json",
  "design/presentation-kit/templates/opportunity.json",
  "design/presentation-kit/templates/proposal.json",
  "design/presentation-kit/templates/outcome.json",
  "design/presentation-kit/README.md",
  "design/work/README.md",
  "presentations/README.md",
  "production/README.md",
  "prototypes/README.md",
];
const workspaceIdPattern = /^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$/;

function todayUtc() {
  return new Date().toISOString().slice(0, 10);
}

function displayNameFromPath(root) {
  return path
    .basename(root)
    .split(/[-_]+/)
    .filter(Boolean)
    .map((part) => `${part[0]?.toUpperCase() ?? ""}${part.slice(1)}`)
    .join(" ");
}

export function slugify(value) {
  return value
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .replace(/^[^a-z]+/, "");
}

function renderTemplate(content, variables) {
  return content.replace(/\{\{([A-Z_]+)\}\}/g, (match, key) => {
    if (!(key in variables)) {
      throw new Error(`Unknown template variable: ${key}`);
    }
    return variables[key];
  });
}

async function readTemplate(relativePath, variables) {
  const content = await readFile(path.join(templateRoot, relativePath), "utf8");
  return renderTemplate(content, variables);
}

export function payloadRoots(payloadRoot = repositoryRoot) {
  return {
    skillSourceRoot: path.join(payloadRoot, "framework", "skills"),
    schemaSourceRoot: path.join(payloadRoot, "framework", "schemas", "v2"),
    guardrailSourceRoot: path.join(payloadRoot, "framework", "guardrails"),
    runtimeSourceRoot: path.join(payloadRoot, "framework", "runtime"),
    playbookSourceRoot: path.join(payloadRoot, "framework", "playbooks"),
    providerSourceRoot: path.join(payloadRoot, "framework", "providers"),
    activitySourceRoot: path.join(payloadRoot, "framework", "activities"),
    referenceSystemSourceRoot: path.join(payloadRoot, "reference-system"),
  };
}

export function renderAgentPointer(skillIds = INITIAL_SKILL_IDS, studioVoice = null) {
  return [
    "<!-- Generated by The Silver Design Framework. Run `silver repair` to regenerate. -->",
    "",
    "# Agent instructions",
    "",
    "Use `design/INDEX.md` to discover this workspace's canonical design artifacts.",
    "Project-local design skills are installed under `.skills/`; read the relevant",
    "`SKILL.md` before performing a supported design task.",
    "",
    "Available design skills:",
    "",
    ...skillIds.map(
      (id) => `- [${id}](.skills/${id}/SKILL.md)`,
    ),
    "",
    "## How the work moves",
    "",
    "Run one skill, then stop. When it finishes, say what it produced, what its",
    "checks actually reported, and two or three things the designer could do next.",
    "Then wait. Recommended next actions are never started automatically, and a",
    "request to explore is not a request to build the whole chain.",
    "",
    "Each guarded invocation runs its own required checks and records the evidence,",
    "so report what the result says rather than assuming it passed.",
    "",
    "Design-system constraints may only be suspended when the user explicitly",
    "requests a partial or suspended prototype constraint profile.",
    "",
    ...(studioVoice
      ? [
          "## Studio voice",
          "",
          studioVoice.body,
          "",
          `If \`${WORKSPACE_PRACTICE_OVERLAY_PATH}\` exists, read it and prefer it. That`,
          "is the personal practice of whoever is working here — their studio voice",
          "and their method overlays — carried in from outside the project and not",
          "committed. Personal preference never relaxes project facts, guardrails,",
          "required guidance, or approval boundaries.",
          "",
        ]
      : []),
  ].join("\n");
}

export async function sourcePackages({
  version,
  payloadRoot = repositoryRoot,
  skillIds = INITIAL_SKILL_IDS,
}) {
  const {
    skillSourceRoot,
    schemaSourceRoot,
    guardrailSourceRoot,
    runtimeSourceRoot,
    playbookSourceRoot,
    providerSourceRoot,
    activitySourceRoot,
    referenceSystemSourceRoot,
  } = payloadRoots(payloadRoot);
  const packages = [];
  for (const id of skillIds) {
    const skill = parse(
      await readUtf8(path.join(skillSourceRoot, id, "skill.yaml")),
    );
    packages.push({
      id,
      type: "skill",
      path: `.skills/${id}`,
      sourcePath: path.join(skillSourceRoot, id),
      version: skill.version,
      ownership: "framework-managed",
      integrity: await treeIntegrity(path.join(skillSourceRoot, id)),
    });
  }
  const providerEntries = (await readdir(providerSourceRoot, { withFileTypes: true }))
    .filter((entry) => entry.isDirectory())
    .sort((left, right) => left.name.localeCompare(right.name));
  for (const entry of providerEntries) {
    const sourcePath = path.join(providerSourceRoot, entry.name);
    const manifest = parse(await readUtf8(path.join(sourcePath, "provider.yaml")));
    packages.push({
      id: manifest.id,
      type: "provider",
      path: `.silver/providers/${manifest.id}`,
      sourcePath,
      version: manifest.version,
      ownership: "framework-managed",
      integrity: await treeIntegrity(sourcePath),
    });
  }
  for (const item of [
    {
      id: "schemas-v2",
      type: "schema-bundle",
      path: ".silver/schemas/v2",
      source: schemaSourceRoot,
    },
    {
      id: "guardrails",
      type: "guardrail-registry",
      path: ".silver/guardrails",
      source: guardrailSourceRoot,
    },
    {
      id: "skill-runtime",
      type: "runtime",
      path: ".silver/runtime",
      source: runtimeSourceRoot,
    },
    {
      id: "default-design-loop",
      type: "playbook",
      path: ".silver/playbooks",
      source: playbookSourceRoot,
    },
    {
      id: "activities",
      type: "activity-catalog",
      path: ".silver/activities",
      source: activitySourceRoot,
    },
  ]) {
    packages.push({
      id: item.id,
      type: item.type,
      path: item.path,
      sourcePath: item.source,
      version,
      ownership: "framework-managed",
      integrity: await treeIntegrity(item.source),
    });
  }
  packages.push({
    id: "reference-system",
    type: "reference-system",
    path: "reference-system",
    sourcePath: referenceSystemSourceRoot,
    version,
    ownership: "copied-and-owned",
    integrity: await treeIntegrity(referenceSystemSourceRoot),
  });
  return packages;
}

async function renderLock({
  version,
  sourceReference,
  indexContent,
  agentPointerContent,
  claudeMemoryContent,
  payloadRoot,
}) {
  const packages = (await sourcePackages({ version, payloadRoot })).map(
    ({ sourcePath, ...record }) => record,
  );

  return stringify({
    schema: "silver/lock/v2",
    framework: {
      version,
      source: {
        type: "local",
        reference: sourceReference,
      },
    },
    packages,
    managed_files: [
      {
        path: "design/INDEX.md",
        owner: "framework-indexer",
        ownership: "generated",
        base_integrity: integrity(indexContent),
      },
      {
        path: "AGENTS.md",
        owner: "framework-agent-pointer",
        ownership: "generated",
        base_integrity: integrity(agentPointerContent),
      },
      {
        path: CLAUDE_MEMORY_PATH,
        owner: "framework-agent-adapter",
        ownership: "generated",
        base_integrity: integrity(claudeMemoryContent),
      },
    ],
  });
}

async function assertSetupTarget(root, { allowExistingCodebase = false } = {}) {
  const manifestPath = path.join(root, "design", "manifest.yaml");
  if (await exists(manifestPath)) {
    return "existing";
  }

  const unexpected = (await listTopLevel(root)).filter(
    (entry) => !allowedBlankEntries.has(entry),
  );
  if (unexpected.length > 0) {
    if (allowExistingCodebase) {
      return "new";
    }
    throw new Error(
      "This folder is not blank and does not contain design/manifest.yaml. " +
        "Existing-codebase adoption is not implemented yet. " +
        `Unexpected entries: ${unexpected.sort().join(", ")}`,
    );
  }
  return "new";
}

export async function setupWorkspace(options = {}) {
  const root = path.resolve(options.root ?? process.cwd());
  await mkdir(root, { recursive: true });
  const mode = await assertSetupTarget(root, {
    allowExistingCodebase: options.allowExistingCodebase,
  });
  const date = options.date ?? todayUtc();
  const version = options.version ?? FRAMEWORK_VERSION;
  const sourceReference =
    options.sourceReference ?? LOCAL_SOURCE_REFERENCE;
  const payloadRoot = options.payloadRoot ?? repositoryRoot;
  const {
    skillSourceRoot,
    schemaSourceRoot,
    guardrailSourceRoot,
    runtimeSourceRoot,
    playbookSourceRoot,
    providerSourceRoot,
    activitySourceRoot,
    referenceSystemSourceRoot,
  } = payloadRoots(payloadRoot);

  let workspaceName;
  let workspaceId;
  let manifest;
  const manifestPath = path.join(root, "design", "manifest.yaml");

  if (mode === "existing") {
    try {
      manifest = parse(await readUtf8(manifestPath));
      workspaceName = manifest?.workspace?.name;
      workspaceId = manifest?.workspace?.id;
    } catch (error) {
      throw new Error(
        `Cannot resume setup because design/manifest.yaml is invalid: ${error.message}`,
      );
    }
    if (!workspaceName || !workspaceId) {
      throw new Error(
        "Cannot resume setup because design/manifest.yaml has no workspace name or id. Run doctor for details.",
      );
    }
    const validation = await validateSchema("manifest.schema.json", manifest);
    if (!validation.valid) {
      throw new Error(
        "Cannot resume setup because design/manifest.yaml violates the v1 contract. " +
          "Run doctor for details.",
      );
    }
  } else {
    workspaceName =
      options.name?.trim() || displayNameFromPath(root) || "Untitled Product";
    workspaceId = options.id?.trim() || slugify(workspaceName);
    if (!workspaceIdPattern.test(workspaceId)) {
      throw new Error(
        `Workspace id "${workspaceId}" must be lowercase kebab-case and begin with a letter.`,
      );
    }
  }

  const variables = {
    DATE: date,
    WORKSPACE_ID: workspaceId,
    WORKSPACE_NAME: workspaceName,
    // A real workspace used to inherit "Blank-workspace fixture for The Silver
    // Design Framework" as its own description. Say something neutral and true
    // until the designer writes the real one.
    WORKSPACE_DESCRIPTION: `Design workspace for ${workspaceName}.`,
  };
  const created = [];
  const preserved = [];
  const lockPath = path.join(root, ".silver", "lock.yaml");
  const hasLock = await exists(lockPath);
  const seedPayload = mode === "new" || !hasLock;

  if (mode === "new") {
    const manifestContent = await readTemplate(
      "design/manifest.yaml",
      variables,
    );
    await writeNewFile(manifestPath, manifestContent);
    created.push("design/manifest.yaml");
    manifest = parse(manifestContent);
  } else {
    preserved.push("design/manifest.yaml");
  }

  for (const relativePath of SEEDED_TEMPLATES) {
    const destination = resolveInside(root, relativePath);
    if (await exists(destination)) {
      preserved.push(relativePath);
      continue;
    }
    const content = await readTemplate(relativePath, variables);
    await writeNewFile(destination, content);
    created.push(relativePath);
  }

  if (seedPayload) {
    for (const id of INITIAL_SKILL_IDS) {
      const skillDestination = path.join(root, ".skills", id);
      const copied = await copyNewTree(
        path.join(skillSourceRoot, id),
        skillDestination,
      );
      created.push(
        ...copied.map((relativePath) =>
          path.posix.join(".skills", id, relativePath.split(path.sep).join("/")),
        ),
      );
    }
    for (const [source, destination] of [
      [schemaSourceRoot, ".silver/schemas/v2"],
      [guardrailSourceRoot, ".silver/guardrails"],
      [runtimeSourceRoot, ".silver/runtime"],
      [playbookSourceRoot, ".silver/playbooks"],
      [providerSourceRoot, ".silver/providers"],
      [activitySourceRoot, ".silver/activities"],
    ]) {
      const copied = await copyNewTree(source, path.join(root, destination));
      created.push(
        ...copied.map((relativePath) =>
          path.posix.join(
            destination,
            relativePath.split(path.sep).join("/"),
          ),
        ),
      );
    }
    const copiedReferenceFiles = await copyNewTree(
      referenceSystemSourceRoot,
      path.join(root, "reference-system"),
    );
    created.push(
      ...copiedReferenceFiles.map((relativePath) =>
        path.posix.join(
          "reference-system",
          relativePath.split(path.sep).join("/"),
        ),
      ),
    );
  }

  const agentPointerPath = path.join(root, "AGENTS.md");
  // The shared default only. A personal studio voice is materialized separately
  // as an untracked file so it never travels in a committed instruction file.
  const agentPointerContent = renderAgentPointer(
    INITIAL_SKILL_IDS,
    await resolveSharedStudioVoice(),
  );
  if (await exists(agentPointerPath)) {
    preserved.push("AGENTS.md");
  } else {
    await writeNewFile(agentPointerPath, agentPointerContent);
    created.push("AGENTS.md");
  }

  // Claude Code reads CLAUDE.md rather than AGENTS.md and discovers skills only
  // under .claude/skills, so a workspace that stops at AGENTS.md and .skills/ is
  // invisible to it. These adapters are generated, never canonical.
  const claudeBlock = renderClaudeBlock(INITIAL_SKILL_IDS);
  const claudeMemoryPath = path.join(root, CLAUDE_MEMORY_PATH);
  const existingClaudeMemory = (await exists(claudeMemoryPath))
    ? await readUtf8(claudeMemoryPath)
    : undefined;
  const claudeMemoryContent = mergeClaudeMemory(existingClaudeMemory, claudeBlock);
  if (existingClaudeMemory === claudeMemoryContent) {
    preserved.push(CLAUDE_MEMORY_PATH);
  } else {
    await writeUtf8(claudeMemoryPath, claudeMemoryContent);
    (existingClaudeMemory === undefined ? created : preserved).push(
      CLAUDE_MEMORY_PATH,
    );
  }
  const { mode: skillLinkMode, linked } = await writeClaudeSkillLinks(
    root,
    INITIAL_SKILL_IDS,
  );
  created.push(...linked);
  created.push(...(await writeLauncher(root)));

  // Ignore the materialized personal practice before anything can commit it.
  const gitignore = await ensureGitignoreEntries(root);
  if (gitignore.changed) created.push(gitignore.path);
  const practiceOverlay = await writeWorkspacePracticeOverlay(root);
  if (practiceOverlay.written) created.push(practiceOverlay.path);

  const indexPath = path.join(root, "design", "INDEX.md");
  const expectedIndexContent = renderIndex(manifest, INITIAL_SKILL_IDS);
  let indexContent;
  if (await exists(indexPath)) {
    indexContent = await readUtf8(indexPath);
    preserved.push("design/INDEX.md");
  } else {
    indexContent = expectedIndexContent;
    await writeNewFile(indexPath, indexContent);
    created.push("design/INDEX.md");
  }

  if (hasLock) {
    preserved.push(".silver/lock.yaml");
  } else {
    const lockContent = await renderLock({
      version,
      sourceReference,
      indexContent,
      agentPointerContent,
      claudeMemoryContent,
      payloadRoot,
    });
    await writeNewFile(lockPath, lockContent);
    created.push(".silver/lock.yaml");
  }

  return {
    root,
    mode,
    workspace: { id: workspaceId, name: workspaceName },
    created,
    preserved,
    agentAdapters: { claudeSkillLinks: skillLinkMode },
    recommendedNextActions: [
      "Review design/product.md and design/brand.md.",
      "Create or refine a portable flow before prototyping when useful.",
      "Run silver doctor to verify the workspace.",
    ],
    // The reference system is a nested npm package. A root `npm install
    // silver-design-framework` does not install its dependencies, so its token
    // build fails until this runs — which was previously documented only inside
    // reference-system/README.md and found the hard way.
    setupSteps: [
      {
        id: "reference-system-dependencies",
        summary:
          "Install the reference system's own dependencies before building tokens.",
        required: false,
        reason:
          "reference-system/ is a separate npm package. Installing Silver does not install its dependencies.",
        commands: [
          "cd reference-system",
          "npm install",
          "npm run build",
        ],
      },
    ],
  };
}
